#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"


platform_resource_urls=()

mkdir -p ${PWD}/resources

for url in "${platform_resource_urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL $url | yq eval '(select(.kind == "Promise") | .spec.clusterSelector) = { "environment": "platform" }' > $PWD/resources/${promise_name}-$(basename $url)
done

worker_resource_urls=()

mkdir -p ${PWD}/resources

for url in "${worker_resource_urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL $url | yq eval '(select(.kind == "Promise") | .spec.clusterSelector) = { "environment": "dev" }' > $PWD/resources/${promise_name}-$(basename $url)
done
