#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources

urls=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/namespace/resource-request.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/slack/resource-request.yaml"
    "https://raw.githubusercontent.com/kzap/platform-demo/main/gitops-repo/kratix-platform-bootstrap/promises/argocd-appset/resource-request.yaml"
    "https://raw.githubusercontent.com/kzap/platform-demo/main/gitops-repo/kratix-platform-bootstrap/promises/github-repo/resource-request.yaml"
)

for url in "${urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL -o $PWD/request-pipeline/resources/${promise_name}-$(basename $url) $url
done
